### ISSUE TITLE
Missing parameters = error instead of defaut value?

### ISSUE THREAD

**Issue by drommk** [heetch/regula#96]
So this is most certainly on purpose, but I realized that trying to evaluate a rule without all the parameters result in an error 

I tried to evaluate this ruleset on staging, providing only the product id : 

```json
{"path":"ride/approach-path/enabled","version":"1I8DpO6ePph6BQYajQ7Gh3K4zy0","ruleset":{"rules":[{"expr":{"kind":"and","operands":[{"kind":"eq","operands":[{"kind":"param","type":"string","name":"product-id"},{"kind":"value","type":"string","data":"es-zaragoza-pro"}]},{"kind":"eq","operands":[{"kind":"param","type":"string","name":"user-id"},{"kind":"value","type":"string","data":"non-valid-uuid"}]}]},"result":{"kind":"value","type":"bool","data":"true"}},{"expr":{"kind":"value","type":"bool","data":"true"},"result":{"kind":"value","type":"bool","data":"false"}}],"type":"bool"}}
``` 

which resulted in this error :
```go.Universe$proxyerror: failed to evaluate ruleset: parameter not found```

Which is explicit enough to make me thing that it behaves as expected. 
So here's my question : why do we throw an error here? 

It seems to me that the initial logic of the rules engine is "keep evaluating until you find a match". So I would expect the result to be `false` by default in this case. 

So if it's on purpose, I'd like to understand the reasoning behind this choice

**Comment by asdine** [comment]
It depends on how strict we want Regula to be.

> It seems to me that the initial logic of the rules engine is "keep evaluating until you find a match". So I would expect the result to be false by default in this case.

This is what we call an implicit behaviour, some engines/interpreters are designed that way, but we chose not to.

Our initial approach was to make Regula predictable, and for that, we needed to make it strict.
Strict systems don't seem natural at first but are very handy when you need to debug problems, if you know the behaviour, you know where to look at.
We'd rather throw errors in the face of the developer during development than present an unexpected value at runtime because she forgot to pass an argument. That's a design choice.
If we realize there was a mistake, in some cases you can't just use the UI to fix that, you need to depoy a new version of the code.

To give an image, we think of a ruleset as the following pseudo Go code:

```go
func evalRuleset(path string, paramA string, paramB bool) (float64, error) {
  switch {
      case res, ok := rulesets[path].Rules[0].Eval(paramA, paramB); ok:
          return res
     case res, ok := rulesets[path].Rules[1].Eval(paramA, paramB); ok:
          return res
      case res, ok := rulesets[path].Rules[2].Eval(paramA, paramB); ok:
          return res
      
  }

  return 0, errors.New("no match")
}
```

1. You can't call the function above without all the parameters because one of the rules might need it.
2. You can't call the function above if you don't provide the right param types
3. If you don't provide a catch all rule, we won't do that for you and return an error

Having strict rulesets allows to not miss any error in production if you tested your code at least once.

In the v0.6, we are introducting the concept of ruleset `Signature`, which indicates clearly:

- the return type
- the param list (name and type)

Developers simply need to always satisfy this signature and they'll always get a result or a no match error (if the author of the ruleset didn't specify a default catchall rule).

- Now, what happens if I need to use a ruleset but I don't have all the parameters?

Currently, there is no choice, you need to pass the parameters, even if they are empty; or create another ruleset

```go
v, err := evalRuleset("some/path", "", true)
```

In the future we might want to add optional parameters? I don't know yet, as always it will depend on the usage and the feedbacks.


Regula is more or less a way to interpret code during runtime, it's like creating a subprocess and running a python script in the middle of an HTTP request. A lot of bad things can happen, so our initial decision was to design it to be as strict as possible:

- only store ASTs, no code -> no syntax error
- strict typing
- no implicit behaviour

As always though, we are open to discussion.

**Comment by drommk** [comment]
I get it. It's opinionated but it makes sense. Basically you decide to let the client implement the fallback strategy and keep the contract explicit. 

I honestly don't know what's more efficient in practice but this is sound approach
